import sql from "./db.js";

async function getAccessInfoForItemId(itemId) {
  // @ts-ignore
  const rows = await sql`
    select access_token, institution_id, user_id from user_institutions where item_id = ${itemId}
  `;
  return rows[0];
}

export { getAccessInfoForItemId };

const getTransactions = {
  transactions: [
    {
      account_id: "p8mv991w1PcAvMlNJLwmcqmKxRjayGcEXWeKm",
      account_owner: null,
      amount: 500,
      authorized_date: null,
      authorized_datetime: null,
      category: ["Travel", "Airlines and Aviation Services"],
      category_id: "22001000",
      check_number: null,
      date: "2022-03-21",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: "United Airlines",
      name: "United Airlines",
      payment_channel: "in store",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "3exMddy1yGHX9apWEbvqhkPlQBo5l7SmDl1xx",
      transaction_type: "special",
      unofficial_currency_code: null,
    },
    {
      account_id: "MeVJoopqpjH3K41xJGeXi4NqwdLGy3temEk7m",
      account_owner: null,
      amount: 6.33,
      authorized_date: "2022-03-18",
      authorized_datetime: null,
      category: ["Travel", "Taxi"],
      category_id: "22016000",
      check_number: null,
      date: "2022-03-19",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: "Uber",
      name: "Uber 072515 SF**POOL**",
      payment_channel: "in store",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "5Zak66vpv4FnyMjKV9xrcjaKQMboKRiG1KPm1",
      transaction_type: "special",
      unofficial_currency_code: null,
    },
    {
      account_id: "p8mv991w1PcAvMlNJLwmcqmKxRjayGcEXWeKm",
      account_owner: null,
      amount: 500,
      authorized_date: null,
      authorized_datetime: null,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      check_number: null,
      date: "2022-03-16",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: "Tectra Inc",
      name: "Tectra Inc",
      payment_channel: "in store",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "x3mv55AlAgtJgMkAqW17TZm7WxEw7Acy34GbZ",
      transaction_type: "place",
      unofficial_currency_code: null,
    },
    {
      account_id: "p8mv991w1PcAvMlNJLwmcqmKxRjayGcEXWeKm",
      account_owner: null,
      amount: 2078.5,
      authorized_date: null,
      authorized_datetime: null,
      category: ["Payment"],
      category_id: "16000000",
      check_number: null,
      date: "2022-03-15",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: "AUTOMATIC PAYMENT - THANK",
      payment_channel: "other",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "4Qd1GG9L9aFZg6mqWAwKcX7bWa8ebqClQb1Pg",
      transaction_type: "special",
      unofficial_currency_code: null,
    },
    {
      account_id: "p8mv991w1PcAvMlNJLwmcqmKxRjayGcEXWeKm",
      account_owner: null,
      amount: 500,
      authorized_date: null,
      authorized_datetime: null,
      category: ["Food and Drink", "Restaurants", "Fast Food"],
      category_id: "13005032",
      check_number: null,
      date: "2022-03-15",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: "KFC",
      name: "KFC",
      payment_channel: "in store",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "aaGQ99zpzBcWkEbjND9gik8AJyvzAVSkB5WMp",
      transaction_type: "place",
      unofficial_currency_code: null,
    },
    {
      account_id: "p8mv991w1PcAvMlNJLwmcqmKxRjayGcEXWeKm",
      account_owner: null,
      amount: 500,
      authorized_date: null,
      authorized_datetime: null,
      category: ["Shops", "Sporting Goods"],
      category_id: "19046000",
      check_number: null,
      date: "2022-03-15",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: "Madison Bicycle Shop",
      name: "Madison Bicycle Shop",
      payment_channel: "in store",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "dP9188xExDtnM5Lq6P39cBylwx6LlXFBjEWpd",
      transaction_type: "place",
      unofficial_currency_code: null,
    },
    {
      account_id: "1jBQmmbZb4fLVM1ngWbNc6BpXk8ZA4tZDxVmV",
      account_owner: null,
      amount: 25,
      authorized_date: "2022-03-05",
      authorized_datetime: null,
      category: ["Payment", "Credit Card"],
      category_id: "16001000",
      check_number: null,
      date: "2022-03-06",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: "CREDIT CARD 3333 PAYMENT *//",
      payment_channel: "other",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "rlov99pEpgfj5PWM9Jv6CX7PJ9ljPmCdeJ5zP",
      transaction_type: "special",
      unofficial_currency_code: null,
    },
    {
      account_id: "MeVJoopqpjH3K41xJGeXi4NqwdLGy3temEk7m",
      account_owner: null,
      amount: 5.4,
      authorized_date: "2022-03-05",
      authorized_datetime: null,
      category: ["Travel", "Taxi"],
      category_id: "22016000",
      check_number: null,
      date: "2022-03-06",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: "Uber",
      name: "Uber 063015 SF**POOL**",
      payment_channel: "in store",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "JPWJ99MLM4trwNaQ6bXAsQVZL6kDZdTQD6rPL",
      transaction_type: "special",
      unofficial_currency_code: null,
    },
    {
      account_id: "ogov99MEMJFmaPxM5ZQ7FP1BbmKxj3tkvzAKx",
      account_owner: null,
      amount: 5850,
      authorized_date: null,
      authorized_datetime: null,
      category: ["Transfer", "Debit"],
      category_id: "21006000",
      check_number: null,
      date: "2022-03-05",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: "ACH Electronic CreditGUSTO PAY 123456",
      payment_channel: "other",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: "ACH",
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "PMAJoo8z8QhaAdj8EQqmcXjB5eWZBaCXP6MRo",
      transaction_type: "special",
      unofficial_currency_code: null,
    },
    {
      account_id: "L7wJooLlL4FBANVvgjr6UePNknXja7hl3RB9d",
      account_owner: null,
      amount: 1000,
      authorized_date: null,
      authorized_datetime: null,
      category: ["Transfer", "Deposit"],
      category_id: "21007000",
      check_number: null,
      date: "2022-03-05",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: "CD DEPOSIT .INITIAL.",
      payment_channel: "other",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "BzWJ994P4DuMR6X5Z83bigGXLx4PXqHzbMKlE",
      transaction_type: "special",
      unofficial_currency_code: null,
    },
    {
      account_id: "p8mv991w1PcAvMlNJLwmcqmKxRjayGcEXWeKm",
      account_owner: null,
      amount: 78.5,
      authorized_date: "2022-03-03",
      authorized_datetime: null,
      category: ["Recreation", "Gyms and Fitness Centers"],
      category_id: "17018000",
      check_number: null,
      date: "2022-03-04",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: "Touchstone",
      name: "Touchstone Climbing",
      payment_channel: "in store",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "NQyJggoKo7Fx3L7mBRAJFXDM59L3MaCX46DwW",
      transaction_type: "place",
      unofficial_currency_code: null,
    },
    {
      account_id: "MeVJoopqpjH3K41xJGeXi4NqwdLGy3temEk7m",
      account_owner: null,
      amount: -500,
      authorized_date: "2022-03-04",
      authorized_datetime: null,
      category: ["Travel", "Airlines and Aviation Services"],
      category_id: "22001000",
      check_number: null,
      date: "2022-03-04",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: "United Airlines",
      name: "United Airlines",
      payment_channel: "other",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "k1ovkk7E7xcx4kj7mnzoF3JwA17ewBsJl6VvV",
      transaction_type: "special",
      unofficial_currency_code: null,
    },
    {
      account_id: "MeVJoopqpjH3K41xJGeXi4NqwdLGy3temEk7m",
      account_owner: null,
      amount: 12,
      authorized_date: "2022-03-03",
      authorized_datetime: null,
      category: ["Food and Drink", "Restaurants", "Fast Food"],
      category_id: "13005032",
      check_number: null,
      date: "2022-03-03",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: "3322",
      },
      merchant_name: "McDonald's",
      name: "McDonald's",
      payment_channel: "in store",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "lLo6ddeEe9CdnbZNqroVINxwmDBvwXfaVoXxy",
      transaction_type: "place",
      unofficial_currency_code: null,
    },
    {
      account_id: "MeVJoopqpjH3K41xJGeXi4NqwdLGy3temEk7m",
      account_owner: null,
      amount: 4.33,
      authorized_date: "2022-03-03",
      authorized_datetime: null,
      category: ["Food and Drink", "Restaurants", "Coffee Shop"],
      category_id: "13005043",
      check_number: null,
      date: "2022-03-03",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: "Starbucks",
      name: "Starbucks",
      payment_channel: "in store",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "qEov99LwLbUJGPlzbpk7T5JVpGjmV4C6zrD3E",
      transaction_type: "place",
      unofficial_currency_code: null,
    },
    {
      account_id: "MeVJoopqpjH3K41xJGeXi4NqwdLGy3temEk7m",
      account_owner: null,
      amount: 89.4,
      authorized_date: "2022-03-01",
      authorized_datetime: null,
      category: ["Food and Drink", "Restaurants"],
      category_id: "13005000",
      check_number: null,
      date: "2022-03-02",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: "Sparkfun",
      name: "SparkFun",
      payment_channel: "in store",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "KjWJZZ1k14fzdN9GkwJofEPa5eG1aKfExpBQ9",
      transaction_type: "place",
      unofficial_currency_code: null,
    },
    {
      account_id: "1jBQmmbZb4fLVM1ngWbNc6BpXk8ZA4tZDxVmV",
      account_owner: null,
      amount: -4.22,
      authorized_date: "2022-03-01",
      authorized_datetime: null,
      category: ["Transfer", "Credit"],
      category_id: "21005000",
      check_number: null,
      date: "2022-03-01",
      datetime: null,
      iso_currency_code: "USD",
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null,
      },
      merchant_name: null,
      name: "INTRST PYMNT",
      payment_channel: "other",
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null,
      },
      pending: false,
      pending_transaction_id: null,
      personal_finance_category: null,
      transaction_code: null,
      transaction_id: "zd1v99kKkauVAJG4Dl35sKgPld8JPBH35Nvna",
      transaction_type: "special",
      unofficial_currency_code: null,
    },
  ],
  accounts: [
    {
      account_id: "MeVJoopqpjH3K41xJGeXi4NqwdLGy3temEk7m",
      balances: {
        available: 100,
        current: 110,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "0000",
      name: "Plaid Checking",
      official_name: "Plaid Gold Standard 0% Interest Checking",
      subtype: "checking",
      type: "depository",
    },
    {
      account_id: "1jBQmmbZb4fLVM1ngWbNc6BpXk8ZA4tZDxVmV",
      balances: {
        available: 200,
        current: 210,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "1111",
      name: "Plaid Saving",
      official_name: "Plaid Silver Standard 0.1% Interest Saving",
      subtype: "savings",
      type: "depository",
    },
    {
      account_id: "L7wJooLlL4FBANVvgjr6UePNknXja7hl3RB9d",
      balances: {
        available: null,
        current: 1000,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "2222",
      name: "Plaid CD",
      official_name: "Plaid Bronze Standard 0.2% Interest CD",
      subtype: "cd",
      type: "depository",
    },
    {
      account_id: "p8mv991w1PcAvMlNJLwmcqmKxRjayGcEXWeKm",
      balances: {
        available: null,
        current: 410,
        iso_currency_code: "USD",
        limit: 2000,
        unofficial_currency_code: null,
      },
      mask: "3333",
      name: "Plaid Credit Card",
      official_name: "Plaid Diamond 12.5% APR Interest Credit Card",
      subtype: "credit card",
      type: "credit",
    },
    {
      account_id: "ogov99MEMJFmaPxM5ZQ7FP1BbmKxj3tkvzAKx",
      balances: {
        available: 43200,
        current: 43200,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "4444",
      name: "Plaid Money Market",
      official_name: "Plaid Platinum Standard 1.85% Interest Money Market",
      subtype: "money market",
      type: "depository",
    },
    {
      account_id: "ge6okk494PHAmMWgq8X6c36ZVNw7GWf4yw9Me",
      balances: {
        available: null,
        current: 320.76,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "5555",
      name: "Plaid IRA",
      official_name: null,
      subtype: "ira",
      type: "investment",
    },
    {
      account_id: "8LPgqqlKlDC9EkgaVPx5t8WKdPaVbMcKNG5rk",
      balances: {
        available: null,
        current: 23631.9805,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "6666",
      name: "Plaid 401k",
      official_name: null,
      subtype: "401k",
      type: "investment",
    },
    {
      account_id: "ExWJvvjejwfAvoXpg4WMclegyDXAakf961zEW",
      balances: {
        available: null,
        current: 65262,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "7777",
      name: "Plaid Student Loan",
      official_name: null,
      subtype: "student",
      type: "loan",
    },
    {
      account_id: "WEA3zzmNmLUQ7DP3zMjmfP5wBvRjKntwBDx4L",
      balances: {
        available: null,
        current: 56302.06,
        iso_currency_code: "USD",
        limit: null,
        unofficial_currency_code: null,
      },
      mask: "8888",
      name: "Plaid Mortgage",
      official_name: null,
      subtype: "mortgage",
      type: "loan",
    },
  ],
};
